DROP TABLE IF EXISTS safety_contacts CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS expenses CASCADE;
DROP TABLE IF EXISTS roadmap_accommodations CASCADE;
DROP TABLE IF EXISTS roadmap_places CASCADE;
DROP TABLE IF EXISTS roadmaps CASCADE;
DROP TABLE IF EXISTS travel_preferences CASCADE;
DROP TABLE IF EXISTS host_profiles CASCADE;
DROP TABLE IF EXISTS hotels CASCADE;
DROP TABLE IF EXISTS places CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roadmap_types CASCADE;
DROP TABLE IF EXISTS group_types CASCADE;
DROP TABLE IF EXISTS travel_types CASCADE;
DROP TABLE IF EXISTS destinations CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TYPE IF EXISTS gender_enum CASCADE;

CREATE TYPE gender_enum AS ENUM ('MALE', 'FEMALE', 'OTHER');

CREATE TABLE roles (
    role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(30) NOT NULL
);

CREATE TABLE destinations (
    destination_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    state VARCHAR(100),
    description TEXT,
    best_season VARCHAR(50)
);

CREATE TABLE travel_types (
    travel_type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE group_types (
    group_type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR(20) NOT NULL
);

CREATE TABLE roadmap_types (
    roadmap_type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR(30) NOT NULL
);

CREATE TABLE users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role_id INT REFERENCES roles(role_id) ON DELETE SET NULL,
    phone VARCHAR(15),
    gender gender_enum,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE places (
    place_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_id INT REFERENCES destinations(destination_id) ON DELETE CASCADE,
    travel_type_id INT REFERENCES travel_types(travel_type_id) ON DELETE SET NULL,
    name VARCHAR(100) NOT NULL,
    latitude DECIMAL(10,8),
    longitude DECIMAL(11,8),
    entry_fee DECIMAL(10,2),
    avg_visit_time INT
);

CREATE TABLE hotels (
    hotel_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_id INT REFERENCES destinations(destination_id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    price_per_night DECIMAL(10,2),
    rating DECIMAL(2,1),
    latitude DECIMAL(10,8),
    longitude DECIMAL(11,8)
);

CREATE TABLE host_profiles (
    host_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES users(user_id) ON DELETE CASCADE,
    destination_id INT REFERENCES destinations(destination_id) ON DELETE SET NULL,
    max_guests INT,
    provides_food BOOLEAN DEFAULT FALSE,
    verified BOOLEAN DEFAULT FALSE,
    voluntary_min_amount DECIMAL(10,2),
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE travel_preferences (
    preference_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES users(user_id) ON DELETE CASCADE,
    travel_type_id INT REFERENCES travel_types(travel_type_id) ON DELETE SET NULL,
    days INT,
    budget DECIMAL(10,2),
    group_type_id INT REFERENCES group_types(group_type_id) ON DELETE SET NULL
);

CREATE TABLE safety_contacts (
    contact_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES users(user_id) ON DELETE CASCADE,
    name VARCHAR(100),
    phone VARCHAR(15)
);

CREATE TABLE roadmaps (
    roadmap_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES users(user_id) ON DELETE CASCADE,
    destination_id INT REFERENCES destinations(destination_id) ON DELETE CASCADE,
    roadmap_type_id INT REFERENCES roadmap_types(roadmap_type_id) ON DELETE SET NULL,
    total_distance DECIMAL(10,2),
    estimated_cost DECIMAL(10,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE roadmap_places (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_id INT REFERENCES roadmaps(roadmap_id) ON DELETE CASCADE,
    place_id INT REFERENCES places(place_id) ON DELETE CASCADE,
    day_number INT,
    visit_order INT,
    estimated_start_time TIME,
    estimated_end_time TIME
);

CREATE TABLE roadmap_accommodations (
    accommodation_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_id INT REFERENCES roadmaps(roadmap_id) ON DELETE CASCADE,
    hotel_id INT REFERENCES hotels(hotel_id) ON DELETE SET NULL,
    day_number INT,
    check_in_time TIME
);

CREATE TABLE expenses (
    expense_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_id INT REFERENCES roadmaps(roadmap_id) ON DELETE CASCADE,
    accommodation DECIMAL(10,2),
    food DECIMAL(10,2),
    transport DECIMAL(10,2),
    entry_fees DECIMAL(10,2),
    currency VARCHAR(10) DEFAULT 'USD',
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE reviews (
    review_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES users(user_id) ON DELETE CASCADE,
    roadmap_id INT REFERENCES roadmaps(roadmap_id) ON DELETE CASCADE,
    rating INT CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);