create type "public"."gender_enum" as enum ('MALE', 'FEMALE', 'OTHER');

drop policy "Users can read their own data" on "public"."users";

revoke delete on table "public"."orders" from "anon";

revoke insert on table "public"."orders" from "anon";

revoke references on table "public"."orders" from "anon";

revoke select on table "public"."orders" from "anon";

revoke trigger on table "public"."orders" from "anon";

revoke truncate on table "public"."orders" from "anon";

revoke update on table "public"."orders" from "anon";

revoke delete on table "public"."orders" from "authenticated";

revoke insert on table "public"."orders" from "authenticated";

revoke references on table "public"."orders" from "authenticated";

revoke select on table "public"."orders" from "authenticated";

revoke trigger on table "public"."orders" from "authenticated";

revoke truncate on table "public"."orders" from "authenticated";

revoke update on table "public"."orders" from "authenticated";

revoke delete on table "public"."orders" from "service_role";

revoke insert on table "public"."orders" from "service_role";

revoke references on table "public"."orders" from "service_role";

revoke select on table "public"."orders" from "service_role";

revoke trigger on table "public"."orders" from "service_role";

revoke truncate on table "public"."orders" from "service_role";

revoke update on table "public"."orders" from "service_role";

alter table "public"."orders" drop constraint "orders_user_id_fkey";

alter table "public"."orders" drop constraint "orders_pkey";

alter table "public"."users" drop constraint "users_pkey";

drop index if exists "public"."orders_pkey";

drop index if exists "public"."users_pkey";

drop table "public"."orders";


  create table "public"."destinations" (
    "destination_id" integer generated by default as identity not null,
    "name" character varying(100) not null,
    "state" character varying(100),
    "description" text,
    "best_season" character varying(50)
      );



  create table "public"."expenses" (
    "expense_id" integer generated by default as identity not null,
    "roadmap_id" integer,
    "accommodation" numeric(10,2),
    "food" numeric(10,2),
    "transport" numeric(10,2),
    "entry_fees" numeric(10,2),
    "currency" character varying(10) default 'USD'::character varying,
    "last_updated" timestamp with time zone default now()
      );



  create table "public"."group_types" (
    "group_type_id" integer generated by default as identity not null,
    "type_name" character varying(20) not null
      );



  create table "public"."host_profiles" (
    "host_id" integer generated by default as identity not null,
    "user_id" integer,
    "destination_id" integer,
    "max_guests" integer,
    "provides_food" boolean default false,
    "verified" boolean default false,
    "voluntary_min_amount" numeric(10,2),
    "is_active" boolean default true
      );



  create table "public"."hotels" (
    "hotel_id" integer generated by default as identity not null,
    "destination_id" integer,
    "name" character varying(100) not null,
    "price_per_night" numeric(10,2),
    "rating" numeric(2,1),
    "latitude" numeric(10,8),
    "longitude" numeric(11,8)
      );



  create table "public"."places" (
    "place_id" integer generated by default as identity not null,
    "destination_id" integer,
    "travel_type_id" integer,
    "name" character varying(100) not null,
    "latitude" numeric(10,8),
    "longitude" numeric(11,8),
    "entry_fee" numeric(10,2),
    "avg_visit_time" integer
      );



  create table "public"."reviews" (
    "review_id" integer generated by default as identity not null,
    "user_id" integer,
    "roadmap_id" integer,
    "rating" integer,
    "comment" text,
    "created_at" timestamp with time zone default now()
      );



  create table "public"."roadmap_accommodations" (
    "accommodation_id" integer generated by default as identity not null,
    "roadmap_id" integer,
    "hotel_id" integer,
    "day_number" integer,
    "check_in_time" time without time zone
      );



  create table "public"."roadmap_places" (
    "id" integer generated by default as identity not null,
    "roadmap_id" integer,
    "place_id" integer,
    "day_number" integer,
    "visit_order" integer,
    "estimated_start_time" time without time zone,
    "estimated_end_time" time without time zone
      );



  create table "public"."roadmap_types" (
    "roadmap_type_id" integer generated by default as identity not null,
    "type_name" character varying(30) not null
      );



  create table "public"."roadmaps" (
    "roadmap_id" integer generated by default as identity not null,
    "user_id" integer,
    "destination_id" integer,
    "roadmap_type_id" integer,
    "total_distance" numeric(10,2),
    "estimated_cost" numeric(10,2),
    "created_at" timestamp with time zone default now()
      );



  create table "public"."roles" (
    "role_id" integer generated by default as identity not null,
    "role_name" character varying(30) not null
      );



  create table "public"."safety_contacts" (
    "contact_id" integer generated by default as identity not null,
    "user_id" integer,
    "name" character varying(100),
    "phone" character varying(15)
      );



  create table "public"."travel_preferences" (
    "preference_id" integer generated by default as identity not null,
    "user_id" integer,
    "travel_type_id" integer,
    "days" integer,
    "budget" numeric(10,2),
    "group_type_id" integer
      );



  create table "public"."travel_types" (
    "travel_type_id" integer generated by default as identity not null,
    "name" character varying(50) not null
      );


alter table "public"."users" drop column "id";

alter table "public"."users" add column "gender" public.gender_enum;

alter table "public"."users" add column "is_active" boolean default true;

alter table "public"."users" add column "password_hash" character varying(255) not null;

alter table "public"."users" add column "phone" character varying(15);

alter table "public"."users" add column "role_id" integer;

alter table "public"."users" add column "user_id" integer generated by default as identity not null;

alter table "public"."users" alter column "email" set data type character varying(100) using "email"::character varying(100);

alter table "public"."users" alter column "name" set data type character varying(100) using "name"::character varying(100);

alter table "public"."users" disable row level security;

CREATE UNIQUE INDEX destinations_pkey ON public.destinations USING btree (destination_id);

CREATE UNIQUE INDEX expenses_pkey ON public.expenses USING btree (expense_id);

CREATE UNIQUE INDEX group_types_pkey ON public.group_types USING btree (group_type_id);

CREATE UNIQUE INDEX host_profiles_pkey ON public.host_profiles USING btree (host_id);

CREATE UNIQUE INDEX hotels_pkey ON public.hotels USING btree (hotel_id);

CREATE UNIQUE INDEX places_pkey ON public.places USING btree (place_id);

CREATE UNIQUE INDEX reviews_pkey ON public.reviews USING btree (review_id);

CREATE UNIQUE INDEX roadmap_accommodations_pkey ON public.roadmap_accommodations USING btree (accommodation_id);

CREATE UNIQUE INDEX roadmap_places_pkey ON public.roadmap_places USING btree (id);

CREATE UNIQUE INDEX roadmap_types_pkey ON public.roadmap_types USING btree (roadmap_type_id);

CREATE UNIQUE INDEX roadmaps_pkey ON public.roadmaps USING btree (roadmap_id);

CREATE UNIQUE INDEX roles_pkey ON public.roles USING btree (role_id);

CREATE UNIQUE INDEX safety_contacts_pkey ON public.safety_contacts USING btree (contact_id);

CREATE UNIQUE INDEX travel_preferences_pkey ON public.travel_preferences USING btree (preference_id);

CREATE UNIQUE INDEX travel_types_pkey ON public.travel_types USING btree (travel_type_id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (user_id);

alter table "public"."destinations" add constraint "destinations_pkey" PRIMARY KEY using index "destinations_pkey";

alter table "public"."expenses" add constraint "expenses_pkey" PRIMARY KEY using index "expenses_pkey";

alter table "public"."group_types" add constraint "group_types_pkey" PRIMARY KEY using index "group_types_pkey";

alter table "public"."host_profiles" add constraint "host_profiles_pkey" PRIMARY KEY using index "host_profiles_pkey";

alter table "public"."hotels" add constraint "hotels_pkey" PRIMARY KEY using index "hotels_pkey";

alter table "public"."places" add constraint "places_pkey" PRIMARY KEY using index "places_pkey";

alter table "public"."reviews" add constraint "reviews_pkey" PRIMARY KEY using index "reviews_pkey";

alter table "public"."roadmap_accommodations" add constraint "roadmap_accommodations_pkey" PRIMARY KEY using index "roadmap_accommodations_pkey";

alter table "public"."roadmap_places" add constraint "roadmap_places_pkey" PRIMARY KEY using index "roadmap_places_pkey";

alter table "public"."roadmap_types" add constraint "roadmap_types_pkey" PRIMARY KEY using index "roadmap_types_pkey";

alter table "public"."roadmaps" add constraint "roadmaps_pkey" PRIMARY KEY using index "roadmaps_pkey";

alter table "public"."roles" add constraint "roles_pkey" PRIMARY KEY using index "roles_pkey";

alter table "public"."safety_contacts" add constraint "safety_contacts_pkey" PRIMARY KEY using index "safety_contacts_pkey";

alter table "public"."travel_preferences" add constraint "travel_preferences_pkey" PRIMARY KEY using index "travel_preferences_pkey";

alter table "public"."travel_types" add constraint "travel_types_pkey" PRIMARY KEY using index "travel_types_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."expenses" add constraint "expenses_roadmap_id_fkey" FOREIGN KEY (roadmap_id) REFERENCES public.roadmaps(roadmap_id) ON DELETE CASCADE not valid;

alter table "public"."expenses" validate constraint "expenses_roadmap_id_fkey";

alter table "public"."host_profiles" add constraint "host_profiles_destination_id_fkey" FOREIGN KEY (destination_id) REFERENCES public.destinations(destination_id) ON DELETE SET NULL not valid;

alter table "public"."host_profiles" validate constraint "host_profiles_destination_id_fkey";

alter table "public"."host_profiles" add constraint "host_profiles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE not valid;

alter table "public"."host_profiles" validate constraint "host_profiles_user_id_fkey";

alter table "public"."hotels" add constraint "hotels_destination_id_fkey" FOREIGN KEY (destination_id) REFERENCES public.destinations(destination_id) ON DELETE CASCADE not valid;

alter table "public"."hotels" validate constraint "hotels_destination_id_fkey";

alter table "public"."places" add constraint "places_destination_id_fkey" FOREIGN KEY (destination_id) REFERENCES public.destinations(destination_id) ON DELETE CASCADE not valid;

alter table "public"."places" validate constraint "places_destination_id_fkey";

alter table "public"."places" add constraint "places_travel_type_id_fkey" FOREIGN KEY (travel_type_id) REFERENCES public.travel_types(travel_type_id) ON DELETE SET NULL not valid;

alter table "public"."places" validate constraint "places_travel_type_id_fkey";

alter table "public"."reviews" add constraint "reviews_rating_check" CHECK (((rating >= 1) AND (rating <= 5))) not valid;

alter table "public"."reviews" validate constraint "reviews_rating_check";

alter table "public"."reviews" add constraint "reviews_roadmap_id_fkey" FOREIGN KEY (roadmap_id) REFERENCES public.roadmaps(roadmap_id) ON DELETE CASCADE not valid;

alter table "public"."reviews" validate constraint "reviews_roadmap_id_fkey";

alter table "public"."reviews" add constraint "reviews_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE not valid;

alter table "public"."reviews" validate constraint "reviews_user_id_fkey";

alter table "public"."roadmap_accommodations" add constraint "roadmap_accommodations_hotel_id_fkey" FOREIGN KEY (hotel_id) REFERENCES public.hotels(hotel_id) ON DELETE SET NULL not valid;

alter table "public"."roadmap_accommodations" validate constraint "roadmap_accommodations_hotel_id_fkey";

alter table "public"."roadmap_accommodations" add constraint "roadmap_accommodations_roadmap_id_fkey" FOREIGN KEY (roadmap_id) REFERENCES public.roadmaps(roadmap_id) ON DELETE CASCADE not valid;

alter table "public"."roadmap_accommodations" validate constraint "roadmap_accommodations_roadmap_id_fkey";

alter table "public"."roadmap_places" add constraint "roadmap_places_place_id_fkey" FOREIGN KEY (place_id) REFERENCES public.places(place_id) ON DELETE CASCADE not valid;

alter table "public"."roadmap_places" validate constraint "roadmap_places_place_id_fkey";

alter table "public"."roadmap_places" add constraint "roadmap_places_roadmap_id_fkey" FOREIGN KEY (roadmap_id) REFERENCES public.roadmaps(roadmap_id) ON DELETE CASCADE not valid;

alter table "public"."roadmap_places" validate constraint "roadmap_places_roadmap_id_fkey";

alter table "public"."roadmaps" add constraint "roadmaps_destination_id_fkey" FOREIGN KEY (destination_id) REFERENCES public.destinations(destination_id) ON DELETE CASCADE not valid;

alter table "public"."roadmaps" validate constraint "roadmaps_destination_id_fkey";

alter table "public"."roadmaps" add constraint "roadmaps_roadmap_type_id_fkey" FOREIGN KEY (roadmap_type_id) REFERENCES public.roadmap_types(roadmap_type_id) ON DELETE SET NULL not valid;

alter table "public"."roadmaps" validate constraint "roadmaps_roadmap_type_id_fkey";

alter table "public"."roadmaps" add constraint "roadmaps_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE not valid;

alter table "public"."roadmaps" validate constraint "roadmaps_user_id_fkey";

alter table "public"."safety_contacts" add constraint "safety_contacts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE not valid;

alter table "public"."safety_contacts" validate constraint "safety_contacts_user_id_fkey";

alter table "public"."travel_preferences" add constraint "travel_preferences_group_type_id_fkey" FOREIGN KEY (group_type_id) REFERENCES public.group_types(group_type_id) ON DELETE SET NULL not valid;

alter table "public"."travel_preferences" validate constraint "travel_preferences_group_type_id_fkey";

alter table "public"."travel_preferences" add constraint "travel_preferences_travel_type_id_fkey" FOREIGN KEY (travel_type_id) REFERENCES public.travel_types(travel_type_id) ON DELETE SET NULL not valid;

alter table "public"."travel_preferences" validate constraint "travel_preferences_travel_type_id_fkey";

alter table "public"."travel_preferences" add constraint "travel_preferences_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE not valid;

alter table "public"."travel_preferences" validate constraint "travel_preferences_user_id_fkey";

alter table "public"."users" add constraint "users_role_id_fkey" FOREIGN KEY (role_id) REFERENCES public.roles(role_id) ON DELETE SET NULL not valid;

alter table "public"."users" validate constraint "users_role_id_fkey";

grant delete on table "public"."destinations" to "anon";

grant insert on table "public"."destinations" to "anon";

grant references on table "public"."destinations" to "anon";

grant select on table "public"."destinations" to "anon";

grant trigger on table "public"."destinations" to "anon";

grant truncate on table "public"."destinations" to "anon";

grant update on table "public"."destinations" to "anon";

grant delete on table "public"."destinations" to "authenticated";

grant insert on table "public"."destinations" to "authenticated";

grant references on table "public"."destinations" to "authenticated";

grant select on table "public"."destinations" to "authenticated";

grant trigger on table "public"."destinations" to "authenticated";

grant truncate on table "public"."destinations" to "authenticated";

grant update on table "public"."destinations" to "authenticated";

grant delete on table "public"."destinations" to "postgres";

grant insert on table "public"."destinations" to "postgres";

grant references on table "public"."destinations" to "postgres";

grant select on table "public"."destinations" to "postgres";

grant trigger on table "public"."destinations" to "postgres";

grant truncate on table "public"."destinations" to "postgres";

grant update on table "public"."destinations" to "postgres";

grant delete on table "public"."destinations" to "service_role";

grant insert on table "public"."destinations" to "service_role";

grant references on table "public"."destinations" to "service_role";

grant select on table "public"."destinations" to "service_role";

grant trigger on table "public"."destinations" to "service_role";

grant truncate on table "public"."destinations" to "service_role";

grant update on table "public"."destinations" to "service_role";

grant delete on table "public"."expenses" to "anon";

grant insert on table "public"."expenses" to "anon";

grant references on table "public"."expenses" to "anon";

grant select on table "public"."expenses" to "anon";

grant trigger on table "public"."expenses" to "anon";

grant truncate on table "public"."expenses" to "anon";

grant update on table "public"."expenses" to "anon";

grant delete on table "public"."expenses" to "authenticated";

grant insert on table "public"."expenses" to "authenticated";

grant references on table "public"."expenses" to "authenticated";

grant select on table "public"."expenses" to "authenticated";

grant trigger on table "public"."expenses" to "authenticated";

grant truncate on table "public"."expenses" to "authenticated";

grant update on table "public"."expenses" to "authenticated";

grant delete on table "public"."expenses" to "postgres";

grant insert on table "public"."expenses" to "postgres";

grant references on table "public"."expenses" to "postgres";

grant select on table "public"."expenses" to "postgres";

grant trigger on table "public"."expenses" to "postgres";

grant truncate on table "public"."expenses" to "postgres";

grant update on table "public"."expenses" to "postgres";

grant delete on table "public"."expenses" to "service_role";

grant insert on table "public"."expenses" to "service_role";

grant references on table "public"."expenses" to "service_role";

grant select on table "public"."expenses" to "service_role";

grant trigger on table "public"."expenses" to "service_role";

grant truncate on table "public"."expenses" to "service_role";

grant update on table "public"."expenses" to "service_role";

grant delete on table "public"."group_types" to "anon";

grant insert on table "public"."group_types" to "anon";

grant references on table "public"."group_types" to "anon";

grant select on table "public"."group_types" to "anon";

grant trigger on table "public"."group_types" to "anon";

grant truncate on table "public"."group_types" to "anon";

grant update on table "public"."group_types" to "anon";

grant delete on table "public"."group_types" to "authenticated";

grant insert on table "public"."group_types" to "authenticated";

grant references on table "public"."group_types" to "authenticated";

grant select on table "public"."group_types" to "authenticated";

grant trigger on table "public"."group_types" to "authenticated";

grant truncate on table "public"."group_types" to "authenticated";

grant update on table "public"."group_types" to "authenticated";

grant delete on table "public"."group_types" to "postgres";

grant insert on table "public"."group_types" to "postgres";

grant references on table "public"."group_types" to "postgres";

grant select on table "public"."group_types" to "postgres";

grant trigger on table "public"."group_types" to "postgres";

grant truncate on table "public"."group_types" to "postgres";

grant update on table "public"."group_types" to "postgres";

grant delete on table "public"."group_types" to "service_role";

grant insert on table "public"."group_types" to "service_role";

grant references on table "public"."group_types" to "service_role";

grant select on table "public"."group_types" to "service_role";

grant trigger on table "public"."group_types" to "service_role";

grant truncate on table "public"."group_types" to "service_role";

grant update on table "public"."group_types" to "service_role";

grant delete on table "public"."host_profiles" to "anon";

grant insert on table "public"."host_profiles" to "anon";

grant references on table "public"."host_profiles" to "anon";

grant select on table "public"."host_profiles" to "anon";

grant trigger on table "public"."host_profiles" to "anon";

grant truncate on table "public"."host_profiles" to "anon";

grant update on table "public"."host_profiles" to "anon";

grant delete on table "public"."host_profiles" to "authenticated";

grant insert on table "public"."host_profiles" to "authenticated";

grant references on table "public"."host_profiles" to "authenticated";

grant select on table "public"."host_profiles" to "authenticated";

grant trigger on table "public"."host_profiles" to "authenticated";

grant truncate on table "public"."host_profiles" to "authenticated";

grant update on table "public"."host_profiles" to "authenticated";

grant delete on table "public"."host_profiles" to "postgres";

grant insert on table "public"."host_profiles" to "postgres";

grant references on table "public"."host_profiles" to "postgres";

grant select on table "public"."host_profiles" to "postgres";

grant trigger on table "public"."host_profiles" to "postgres";

grant truncate on table "public"."host_profiles" to "postgres";

grant update on table "public"."host_profiles" to "postgres";

grant delete on table "public"."host_profiles" to "service_role";

grant insert on table "public"."host_profiles" to "service_role";

grant references on table "public"."host_profiles" to "service_role";

grant select on table "public"."host_profiles" to "service_role";

grant trigger on table "public"."host_profiles" to "service_role";

grant truncate on table "public"."host_profiles" to "service_role";

grant update on table "public"."host_profiles" to "service_role";

grant delete on table "public"."hotels" to "anon";

grant insert on table "public"."hotels" to "anon";

grant references on table "public"."hotels" to "anon";

grant select on table "public"."hotels" to "anon";

grant trigger on table "public"."hotels" to "anon";

grant truncate on table "public"."hotels" to "anon";

grant update on table "public"."hotels" to "anon";

grant delete on table "public"."hotels" to "authenticated";

grant insert on table "public"."hotels" to "authenticated";

grant references on table "public"."hotels" to "authenticated";

grant select on table "public"."hotels" to "authenticated";

grant trigger on table "public"."hotels" to "authenticated";

grant truncate on table "public"."hotels" to "authenticated";

grant update on table "public"."hotels" to "authenticated";

grant delete on table "public"."hotels" to "postgres";

grant insert on table "public"."hotels" to "postgres";

grant references on table "public"."hotels" to "postgres";

grant select on table "public"."hotels" to "postgres";

grant trigger on table "public"."hotels" to "postgres";

grant truncate on table "public"."hotels" to "postgres";

grant update on table "public"."hotels" to "postgres";

grant delete on table "public"."hotels" to "service_role";

grant insert on table "public"."hotels" to "service_role";

grant references on table "public"."hotels" to "service_role";

grant select on table "public"."hotels" to "service_role";

grant trigger on table "public"."hotels" to "service_role";

grant truncate on table "public"."hotels" to "service_role";

grant update on table "public"."hotels" to "service_role";

grant delete on table "public"."places" to "anon";

grant insert on table "public"."places" to "anon";

grant references on table "public"."places" to "anon";

grant select on table "public"."places" to "anon";

grant trigger on table "public"."places" to "anon";

grant truncate on table "public"."places" to "anon";

grant update on table "public"."places" to "anon";

grant delete on table "public"."places" to "authenticated";

grant insert on table "public"."places" to "authenticated";

grant references on table "public"."places" to "authenticated";

grant select on table "public"."places" to "authenticated";

grant trigger on table "public"."places" to "authenticated";

grant truncate on table "public"."places" to "authenticated";

grant update on table "public"."places" to "authenticated";

grant delete on table "public"."places" to "postgres";

grant insert on table "public"."places" to "postgres";

grant references on table "public"."places" to "postgres";

grant select on table "public"."places" to "postgres";

grant trigger on table "public"."places" to "postgres";

grant truncate on table "public"."places" to "postgres";

grant update on table "public"."places" to "postgres";

grant delete on table "public"."places" to "service_role";

grant insert on table "public"."places" to "service_role";

grant references on table "public"."places" to "service_role";

grant select on table "public"."places" to "service_role";

grant trigger on table "public"."places" to "service_role";

grant truncate on table "public"."places" to "service_role";

grant update on table "public"."places" to "service_role";

grant delete on table "public"."reviews" to "anon";

grant insert on table "public"."reviews" to "anon";

grant references on table "public"."reviews" to "anon";

grant select on table "public"."reviews" to "anon";

grant trigger on table "public"."reviews" to "anon";

grant truncate on table "public"."reviews" to "anon";

grant update on table "public"."reviews" to "anon";

grant delete on table "public"."reviews" to "authenticated";

grant insert on table "public"."reviews" to "authenticated";

grant references on table "public"."reviews" to "authenticated";

grant select on table "public"."reviews" to "authenticated";

grant trigger on table "public"."reviews" to "authenticated";

grant truncate on table "public"."reviews" to "authenticated";

grant update on table "public"."reviews" to "authenticated";

grant delete on table "public"."reviews" to "postgres";

grant insert on table "public"."reviews" to "postgres";

grant references on table "public"."reviews" to "postgres";

grant select on table "public"."reviews" to "postgres";

grant trigger on table "public"."reviews" to "postgres";

grant truncate on table "public"."reviews" to "postgres";

grant update on table "public"."reviews" to "postgres";

grant delete on table "public"."reviews" to "service_role";

grant insert on table "public"."reviews" to "service_role";

grant references on table "public"."reviews" to "service_role";

grant select on table "public"."reviews" to "service_role";

grant trigger on table "public"."reviews" to "service_role";

grant truncate on table "public"."reviews" to "service_role";

grant update on table "public"."reviews" to "service_role";

grant delete on table "public"."roadmap_accommodations" to "anon";

grant insert on table "public"."roadmap_accommodations" to "anon";

grant references on table "public"."roadmap_accommodations" to "anon";

grant select on table "public"."roadmap_accommodations" to "anon";

grant trigger on table "public"."roadmap_accommodations" to "anon";

grant truncate on table "public"."roadmap_accommodations" to "anon";

grant update on table "public"."roadmap_accommodations" to "anon";

grant delete on table "public"."roadmap_accommodations" to "authenticated";

grant insert on table "public"."roadmap_accommodations" to "authenticated";

grant references on table "public"."roadmap_accommodations" to "authenticated";

grant select on table "public"."roadmap_accommodations" to "authenticated";

grant trigger on table "public"."roadmap_accommodations" to "authenticated";

grant truncate on table "public"."roadmap_accommodations" to "authenticated";

grant update on table "public"."roadmap_accommodations" to "authenticated";

grant delete on table "public"."roadmap_accommodations" to "postgres";

grant insert on table "public"."roadmap_accommodations" to "postgres";

grant references on table "public"."roadmap_accommodations" to "postgres";

grant select on table "public"."roadmap_accommodations" to "postgres";

grant trigger on table "public"."roadmap_accommodations" to "postgres";

grant truncate on table "public"."roadmap_accommodations" to "postgres";

grant update on table "public"."roadmap_accommodations" to "postgres";

grant delete on table "public"."roadmap_accommodations" to "service_role";

grant insert on table "public"."roadmap_accommodations" to "service_role";

grant references on table "public"."roadmap_accommodations" to "service_role";

grant select on table "public"."roadmap_accommodations" to "service_role";

grant trigger on table "public"."roadmap_accommodations" to "service_role";

grant truncate on table "public"."roadmap_accommodations" to "service_role";

grant update on table "public"."roadmap_accommodations" to "service_role";

grant delete on table "public"."roadmap_places" to "anon";

grant insert on table "public"."roadmap_places" to "anon";

grant references on table "public"."roadmap_places" to "anon";

grant select on table "public"."roadmap_places" to "anon";

grant trigger on table "public"."roadmap_places" to "anon";

grant truncate on table "public"."roadmap_places" to "anon";

grant update on table "public"."roadmap_places" to "anon";

grant delete on table "public"."roadmap_places" to "authenticated";

grant insert on table "public"."roadmap_places" to "authenticated";

grant references on table "public"."roadmap_places" to "authenticated";

grant select on table "public"."roadmap_places" to "authenticated";

grant trigger on table "public"."roadmap_places" to "authenticated";

grant truncate on table "public"."roadmap_places" to "authenticated";

grant update on table "public"."roadmap_places" to "authenticated";

grant delete on table "public"."roadmap_places" to "postgres";

grant insert on table "public"."roadmap_places" to "postgres";

grant references on table "public"."roadmap_places" to "postgres";

grant select on table "public"."roadmap_places" to "postgres";

grant trigger on table "public"."roadmap_places" to "postgres";

grant truncate on table "public"."roadmap_places" to "postgres";

grant update on table "public"."roadmap_places" to "postgres";

grant delete on table "public"."roadmap_places" to "service_role";

grant insert on table "public"."roadmap_places" to "service_role";

grant references on table "public"."roadmap_places" to "service_role";

grant select on table "public"."roadmap_places" to "service_role";

grant trigger on table "public"."roadmap_places" to "service_role";

grant truncate on table "public"."roadmap_places" to "service_role";

grant update on table "public"."roadmap_places" to "service_role";

grant delete on table "public"."roadmap_types" to "anon";

grant insert on table "public"."roadmap_types" to "anon";

grant references on table "public"."roadmap_types" to "anon";

grant select on table "public"."roadmap_types" to "anon";

grant trigger on table "public"."roadmap_types" to "anon";

grant truncate on table "public"."roadmap_types" to "anon";

grant update on table "public"."roadmap_types" to "anon";

grant delete on table "public"."roadmap_types" to "authenticated";

grant insert on table "public"."roadmap_types" to "authenticated";

grant references on table "public"."roadmap_types" to "authenticated";

grant select on table "public"."roadmap_types" to "authenticated";

grant trigger on table "public"."roadmap_types" to "authenticated";

grant truncate on table "public"."roadmap_types" to "authenticated";

grant update on table "public"."roadmap_types" to "authenticated";

grant delete on table "public"."roadmap_types" to "postgres";

grant insert on table "public"."roadmap_types" to "postgres";

grant references on table "public"."roadmap_types" to "postgres";

grant select on table "public"."roadmap_types" to "postgres";

grant trigger on table "public"."roadmap_types" to "postgres";

grant truncate on table "public"."roadmap_types" to "postgres";

grant update on table "public"."roadmap_types" to "postgres";

grant delete on table "public"."roadmap_types" to "service_role";

grant insert on table "public"."roadmap_types" to "service_role";

grant references on table "public"."roadmap_types" to "service_role";

grant select on table "public"."roadmap_types" to "service_role";

grant trigger on table "public"."roadmap_types" to "service_role";

grant truncate on table "public"."roadmap_types" to "service_role";

grant update on table "public"."roadmap_types" to "service_role";

grant delete on table "public"."roadmaps" to "anon";

grant insert on table "public"."roadmaps" to "anon";

grant references on table "public"."roadmaps" to "anon";

grant select on table "public"."roadmaps" to "anon";

grant trigger on table "public"."roadmaps" to "anon";

grant truncate on table "public"."roadmaps" to "anon";

grant update on table "public"."roadmaps" to "anon";

grant delete on table "public"."roadmaps" to "authenticated";

grant insert on table "public"."roadmaps" to "authenticated";

grant references on table "public"."roadmaps" to "authenticated";

grant select on table "public"."roadmaps" to "authenticated";

grant trigger on table "public"."roadmaps" to "authenticated";

grant truncate on table "public"."roadmaps" to "authenticated";

grant update on table "public"."roadmaps" to "authenticated";

grant delete on table "public"."roadmaps" to "postgres";

grant insert on table "public"."roadmaps" to "postgres";

grant references on table "public"."roadmaps" to "postgres";

grant select on table "public"."roadmaps" to "postgres";

grant trigger on table "public"."roadmaps" to "postgres";

grant truncate on table "public"."roadmaps" to "postgres";

grant update on table "public"."roadmaps" to "postgres";

grant delete on table "public"."roadmaps" to "service_role";

grant insert on table "public"."roadmaps" to "service_role";

grant references on table "public"."roadmaps" to "service_role";

grant select on table "public"."roadmaps" to "service_role";

grant trigger on table "public"."roadmaps" to "service_role";

grant truncate on table "public"."roadmaps" to "service_role";

grant update on table "public"."roadmaps" to "service_role";

grant delete on table "public"."roles" to "anon";

grant insert on table "public"."roles" to "anon";

grant references on table "public"."roles" to "anon";

grant select on table "public"."roles" to "anon";

grant trigger on table "public"."roles" to "anon";

grant truncate on table "public"."roles" to "anon";

grant update on table "public"."roles" to "anon";

grant delete on table "public"."roles" to "authenticated";

grant insert on table "public"."roles" to "authenticated";

grant references on table "public"."roles" to "authenticated";

grant select on table "public"."roles" to "authenticated";

grant trigger on table "public"."roles" to "authenticated";

grant truncate on table "public"."roles" to "authenticated";

grant update on table "public"."roles" to "authenticated";

grant delete on table "public"."roles" to "postgres";

grant insert on table "public"."roles" to "postgres";

grant references on table "public"."roles" to "postgres";

grant select on table "public"."roles" to "postgres";

grant trigger on table "public"."roles" to "postgres";

grant truncate on table "public"."roles" to "postgres";

grant update on table "public"."roles" to "postgres";

grant delete on table "public"."roles" to "service_role";

grant insert on table "public"."roles" to "service_role";

grant references on table "public"."roles" to "service_role";

grant select on table "public"."roles" to "service_role";

grant trigger on table "public"."roles" to "service_role";

grant truncate on table "public"."roles" to "service_role";

grant update on table "public"."roles" to "service_role";

grant delete on table "public"."safety_contacts" to "anon";

grant insert on table "public"."safety_contacts" to "anon";

grant references on table "public"."safety_contacts" to "anon";

grant select on table "public"."safety_contacts" to "anon";

grant trigger on table "public"."safety_contacts" to "anon";

grant truncate on table "public"."safety_contacts" to "anon";

grant update on table "public"."safety_contacts" to "anon";

grant delete on table "public"."safety_contacts" to "authenticated";

grant insert on table "public"."safety_contacts" to "authenticated";

grant references on table "public"."safety_contacts" to "authenticated";

grant select on table "public"."safety_contacts" to "authenticated";

grant trigger on table "public"."safety_contacts" to "authenticated";

grant truncate on table "public"."safety_contacts" to "authenticated";

grant update on table "public"."safety_contacts" to "authenticated";

grant delete on table "public"."safety_contacts" to "postgres";

grant insert on table "public"."safety_contacts" to "postgres";

grant references on table "public"."safety_contacts" to "postgres";

grant select on table "public"."safety_contacts" to "postgres";

grant trigger on table "public"."safety_contacts" to "postgres";

grant truncate on table "public"."safety_contacts" to "postgres";

grant update on table "public"."safety_contacts" to "postgres";

grant delete on table "public"."safety_contacts" to "service_role";

grant insert on table "public"."safety_contacts" to "service_role";

grant references on table "public"."safety_contacts" to "service_role";

grant select on table "public"."safety_contacts" to "service_role";

grant trigger on table "public"."safety_contacts" to "service_role";

grant truncate on table "public"."safety_contacts" to "service_role";

grant update on table "public"."safety_contacts" to "service_role";

grant delete on table "public"."travel_preferences" to "anon";

grant insert on table "public"."travel_preferences" to "anon";

grant references on table "public"."travel_preferences" to "anon";

grant select on table "public"."travel_preferences" to "anon";

grant trigger on table "public"."travel_preferences" to "anon";

grant truncate on table "public"."travel_preferences" to "anon";

grant update on table "public"."travel_preferences" to "anon";

grant delete on table "public"."travel_preferences" to "authenticated";

grant insert on table "public"."travel_preferences" to "authenticated";

grant references on table "public"."travel_preferences" to "authenticated";

grant select on table "public"."travel_preferences" to "authenticated";

grant trigger on table "public"."travel_preferences" to "authenticated";

grant truncate on table "public"."travel_preferences" to "authenticated";

grant update on table "public"."travel_preferences" to "authenticated";

grant delete on table "public"."travel_preferences" to "postgres";

grant insert on table "public"."travel_preferences" to "postgres";

grant references on table "public"."travel_preferences" to "postgres";

grant select on table "public"."travel_preferences" to "postgres";

grant trigger on table "public"."travel_preferences" to "postgres";

grant truncate on table "public"."travel_preferences" to "postgres";

grant update on table "public"."travel_preferences" to "postgres";

grant delete on table "public"."travel_preferences" to "service_role";

grant insert on table "public"."travel_preferences" to "service_role";

grant references on table "public"."travel_preferences" to "service_role";

grant select on table "public"."travel_preferences" to "service_role";

grant trigger on table "public"."travel_preferences" to "service_role";

grant truncate on table "public"."travel_preferences" to "service_role";

grant update on table "public"."travel_preferences" to "service_role";

grant delete on table "public"."travel_types" to "anon";

grant insert on table "public"."travel_types" to "anon";

grant references on table "public"."travel_types" to "anon";

grant select on table "public"."travel_types" to "anon";

grant trigger on table "public"."travel_types" to "anon";

grant truncate on table "public"."travel_types" to "anon";

grant update on table "public"."travel_types" to "anon";

grant delete on table "public"."travel_types" to "authenticated";

grant insert on table "public"."travel_types" to "authenticated";

grant references on table "public"."travel_types" to "authenticated";

grant select on table "public"."travel_types" to "authenticated";

grant trigger on table "public"."travel_types" to "authenticated";

grant truncate on table "public"."travel_types" to "authenticated";

grant update on table "public"."travel_types" to "authenticated";

grant delete on table "public"."travel_types" to "postgres";

grant insert on table "public"."travel_types" to "postgres";

grant references on table "public"."travel_types" to "postgres";

grant select on table "public"."travel_types" to "postgres";

grant trigger on table "public"."travel_types" to "postgres";

grant truncate on table "public"."travel_types" to "postgres";

grant update on table "public"."travel_types" to "postgres";

grant delete on table "public"."travel_types" to "service_role";

grant insert on table "public"."travel_types" to "service_role";

grant references on table "public"."travel_types" to "service_role";

grant select on table "public"."travel_types" to "service_role";

grant trigger on table "public"."travel_types" to "service_role";

grant truncate on table "public"."travel_types" to "service_role";

grant update on table "public"."travel_types" to "service_role";

grant delete on table "public"."users" to "postgres";

grant insert on table "public"."users" to "postgres";

grant references on table "public"."users" to "postgres";

grant select on table "public"."users" to "postgres";

grant trigger on table "public"."users" to "postgres";

grant truncate on table "public"."users" to "postgres";

grant update on table "public"."users" to "postgres";
