-- Add destination_id to travel_preferences
ALTER TABLE public.travel_preferences 
ADD COLUMN destination_id INTEGER REFERENCES public.destinations(destination_id) ON DELETE SET NULL;

-- Create place_distances table
CREATE TABLE IF NOT EXISTS public.place_distances (
    distance_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_a_id INTEGER REFERENCES public.places(place_id) ON DELETE CASCADE,
    place_b_id INTEGER REFERENCES public.places(place_id) ON DELETE CASCADE,
    distance NUMERIC(10,2) NOT NULL, -- distance in km
    UNIQUE(place_a_id, place_b_id)
);

-- Grant permissions
GRANT ALL ON TABLE public.place_distances TO anon, authenticated, service_role, postgres;
