-- Create host_registrations table for pending host registration submissions
CREATE TABLE IF NOT EXISTS "public"."host_registrations" (
    "id" integer generated by default as identity not null,
    "user_id" integer,
    "name" character varying(100) not null,
    "phone" character varying(15),
    "state" character varying(100),
    "destination" character varying(100),
    "address" text,
    "description" text,
    "amenities" text[],
    "property_type" character varying(50),
    "max_guests" integer default 1,
    "provides_food" boolean default false,
    "pricing_info" text,
    "image_urls" text[],
    "status" character varying(20) default 'pending',
    "rejection_reason" text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
);

CREATE UNIQUE INDEX IF NOT EXISTS host_registrations_pkey ON public.host_registrations USING btree (id);
ALTER TABLE "public"."host_registrations" ADD CONSTRAINT "host_registrations_pkey" PRIMARY KEY USING INDEX "host_registrations_pkey";

-- Add foreign key to users table
ALTER TABLE "public"."host_registrations" ADD CONSTRAINT "host_registrations_user_id_fkey"
    FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE "public"."host_registrations" VALIDATE CONSTRAINT "host_registrations_user_id_fkey";

-- Grant permissions (same pattern as other tables)
GRANT ALL ON TABLE "public"."host_registrations" TO "anon";
GRANT ALL ON TABLE "public"."host_registrations" TO "authenticated";
GRANT ALL ON TABLE "public"."host_registrations" TO "postgres";
GRANT ALL ON TABLE "public"."host_registrations" TO "service_role";
